-- One-line AI digest of what a judgment decides ("issue line"), shown
-- under the title in the Live Digest. Generated by Claude Haiku during
-- the daily ingest cron; NULL until generated.
ALTER TABLE judgments
  ADD COLUMN IF NOT EXISTS issue_line TEXT;
